# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Kubrix < Formula
  desc ""
  homepage "https://kubrix.io"
  version "0.1.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/suxess-it/kubriX-cli/releases/download/v0.1.0/kubriX-cli_Darwin_x86_64.tar.gz"
      sha256 "ad56ecb8003ce4c31122899c83563ba927a1116aa41d3aacaae9f5060c0e7155"

      define_method(:install) do
        bin.install "kubriX-cli"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/suxess-it/kubriX-cli/releases/download/v0.1.0/kubriX-cli_Darwin_arm64.tar.gz"
      sha256 "de7513ea2e563607dce4e9523435bb885a2703531770cba8abe9c6ebe90e1038"

      define_method(:install) do
        bin.install "kubriX-cli"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/suxess-it/kubriX-cli/releases/download/v0.1.0/kubriX-cli_Linux_x86_64.tar.gz"
      sha256 "8d21ff1b8768587f5ebf0bd36f8e2c717b8361b2b33030715a544dcdd21a5674"
      define_method(:install) do
        bin.install "kubriX-cli"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/suxess-it/kubriX-cli/releases/download/v0.1.0/kubriX-cli_Linux_arm64.tar.gz"
      sha256 "29d11de8dff2d6b28a188eebc076559b3b1a5b5c6d5ce9f66a6b298b164405ab"
      define_method(:install) do
        bin.install "kubriX-cli"
      end
    end
  end
end
