# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Kubrix < Formula
  desc ""
  homepage "https://kubrix.io"
  version "0.1.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/suxess-it/kubriX-cli/releases/download/v0.1.1/kubriX-cli_Darwin_x86_64.tar.gz"
      sha256 "8d4128783e279228d34c97d2f533173b803a9c5f62c593bddad2d3d205fcf768"

      define_method(:install) do
        bin.install "kubrix"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/suxess-it/kubriX-cli/releases/download/v0.1.1/kubriX-cli_Darwin_arm64.tar.gz"
      sha256 "1d9a06092428f6a649c910facefe3af76f0a0294a7a4eb223d90c3798a8d62b0"

      define_method(:install) do
        bin.install "kubrix"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/suxess-it/kubriX-cli/releases/download/v0.1.1/kubriX-cli_Linux_x86_64.tar.gz"
      sha256 "8500640b26c2c4085332449c59b267e4ca644a6a04c4d9b331a55955e97f09dc"
      define_method(:install) do
        bin.install "kubrix"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/suxess-it/kubriX-cli/releases/download/v0.1.1/kubriX-cli_Linux_arm64.tar.gz"
      sha256 "bd6259bd3eb2ea74916e7e6a7ce8069a3978b9d939282fd102ec98e4d934df74"
      define_method(:install) do
        bin.install "kubrix"
      end
    end
  end
end
